name: Build and Deploy to Google Play

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle Build Files
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant Execute Permission to Gradle Wrapper
      run: chmod +x gradlew

    - name: Build Release App Bundle (AAB)
      run: ./gradlew bundleRelease
      env:
        KEYSTORE_PATH: ""
        STORE_PASSWORD: ""
        KEY_PASSWORD: ""

    - name: Sign Android Release App Bundle
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.PLAY_STORE_KEYSTORE_BASE64 }}
        alias: ${{ secrets.PLAY_STORE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.PLAY_STORE_STORE_PASSWORD }}
        keyPassword: ${{ secrets.PLAY_STORE_KEY_PASSWORD }}

    - name: Upload Signed App Bundle to Google Play Console
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonRaw: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
        packageName: com.aistudio.athlepulse.atlp
        releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
        track: internal # Options: internal, alpha, beta, production
        status: completed
